const P_LIKES = {
    text    : {
        animals     : .2,
        food        : .1,
        news        : .4,
        memories    : .5,
        'an opinion': .7,
        'a place'   : .4,
        'a dance'   : .1,
    },
    photo   : {
        animals     : .9,
        food        : .7,
        news        : .4,
        memories    : .9,
        'an opinion': .2,
        'a place'   : .8,
        'a dance'   : .5,
    },
    video   : {
        animals     : .7,
        food        : .7,
        news        : .5,
        memories    : .7,
        'an opinion': .6,
        'a place'   : .7,
        'a dance'   : .9,        
    },
    song    : {
        animals     : .1,
        food        : .1,
        news        : .1,
        memories    : .9,
        'an opinion': .1,
        'a place'   : .1,
        'a dance'   : .7,       
    },
    link    : {
        animals     : .3,
        food        : .8,
        news        : .7,
        memories    : .1,
        'an opinion': .1,
        'a place'   : .2,
        'a dance'   : .1,       
    },
    story   : {
        animals     : .8,
        food        : .5,
        news        : .6,
        memories    : .3,
        'an opinion': .7,
        'a place'   : .7,
        'a dance'   : .9,        
    },
}

const P_SHARE = {
    text    : {
        animals     : 0.3,
        food        : 0.4,
        news        : 0.7,
        memories    : 0.3,
        'an opinion': 0.6,
        'a place'   : 0.2,
        'a dance'   : 0.1,
    },
    photo   : {
        animals     : 0.4,
        food        : 0.3,
        news        : 0.6,
        memories    : 0.7,
        'an opinion': 0.2,
        'a place'   : 0.4,
        'a dance'   : 0.2,
    },
    video   : {
        animals     : 0.6,
        food        : 0.8,
        news        : 0.8,
        memories    : 0.8,
        'an opinion': 0.5,
        'a place'   : 0.5,
        'a dance'   : 0.7,        
    },
    song    : {
        animals     : 0.1,
        food        : 0.1,
        news        : 0.1,
        memories    : 0.9,
        'an opinion': 0.1,
        'a place'   : 0.1,
        'a dance'   : 0.8,       
    },
    link    : {
        animals     : 0.3,
        food        : 0.8,
        news        : 0.9,
        memories    : 0.1,
        'an opinion': 0.1,
        'a place'   : 0.2,
        'a dance'   : 0.1,       
    },
    story   : {
        animals     : 0.1,
        food        : 0.8,
        news        : 0.5,
        memories    : 0.3,
        'an opinion': 0.6,
        'a place'   : 0.9,
        'a dance'   : 0.9,        
    },
}

const SHORT_NUMBER_FORMAT = {
    notation                : "compact",
    compactDisplay          : "short",
    minimumFractionDigits   : 1,
    maximumFractionDigits   : 2
  }